foodapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'foodapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /foodapp/recipes/5/
    url(r'^recipes/(?P<recipe_id>[0-9]+)/$', views.recipe_detail, name='recipe_detail'),
    # ex: foodapp/3
    url(r'^(?P<ingredient_id>[0-9]+)/$', views.ingredient_detail, name='ingredient_detail'),
    # ex: /foodapp/5/preferences-ingredient/
    url(r'^(?P<ingredient_id>[0-9]+)/preferences-ingredient/$', views.preferences_ingredient, name='preferences_ingredient'),
    # ex: /foodapp/5/rank-ingredient/
    url(r'^(?P<ingredient_id>[0-9]+)/rank-ingredient/$', views.rank_ingredient, name='rank_ingredient'),
    #  /foodapp/run-model/
    url(r'^run-model/$', views.run_model, name='run_model'),
    url(r'^model-results/$', views.model_results, name='model_results'),
    url(r'^rank-output/$', views.rank_output, name='rank_output'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^foodapp/', include('foodapp.urls')),
    url(r'^admin/', admin.site.urls),
]

foodapp/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.core.validators import validate_comma_separated_integer_list
from django.contrib.postgres.fields import ArrayField


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Ingredient(models.Model):
	iid = models.IntegerField(unique=True) # Need to specify the id as Django creates it automatically right ?
	ingredient_name = models.CharField(max_length=200, unique=True)
	# recipe_id = models.ManyToManyField(Recipe, symmetrical = True) # DO IT LATER
	user_preference = models.FloatField(default=0)
	serving_size = models.FloatField(default=0)
	unit = models.CharField(max_length=200, default=0)
	package_size = models.FloatField(default=0) 
	price = models.FloatField(default=0)
	calories =  models.FloatField(default=0)
	fat = models.FloatField(default=0)
	fiber = models.FloatField(default=0)
	sugar = models.FloatField(default=0)
	protein = models.FloatField(default=0)

	def __str__(self):
		return self.ingredient_name


class Relationship(models.Model):
	rel_id = models.IntegerField(unique=True)
	ingredient_name = models.CharField(max_length=200)
	recipe_id = models.IntegerField(default=0)
	ingredient_id = models.IntegerField(default=0)

	def __str__(self):
		#return "Recipe-ingredient pair: recipe '{0}', ingredient '{1}'".format(self.recipe_id, self.ingredient_id)
		return  "Recipe-ingredient pair: recipe %d, ingredient %d " % (self.recipe_id, self.ingredient_id)

class Recipe(models.Model):
	rid = models.IntegerField(unique=True)
	#ingredient_id = models.ManyToManyField(Relationship, symmetrical = True) # END UP WITH AN INTEGRITY ERROR 
	recipe_name = models.CharField(max_length=200, unique=True)
	number_steps = models.IntegerField(default=0)
	instructions = models.TextField()
	ingredients = ArrayField((models.IntegerField()))
	ranking = models.FloatField(default=5)



	def __str__(self):
		return self.recipe_name		

foodapp/forms.py
from django import forms
from django.forms import formset_factory
from django.forms.formsets import BaseFormSet
from foodapp.models import Recipe, Ingredient


class RankRecipeForm(forms.ModelForm):
	#recipe_name = forms.CharField(widget=forms.HiddenInput(), required=False)

	# intialize the data maybe ??

	# http://stackoverflow.com/questions/6472269/django-modelform-with-initial-data-not-shown-on-redisplay

	class Meta:
		model = Recipe
		fields = ['rid', 'recipe_name', 'ranking']
		widgets = {'rid': forms.HiddenInput(), 'recipe_name' : forms.TextInput(attrs={'readonly':'readonly'}), 
		'ranking' : forms.NumberInput(attrs={'min': 0, 'max': 10})}
		exclude = ('ingredients','number_steps','instructions' ) # exclude everything but ranking!


#RankRecipeFormSet = formset_factory(RankRecipeForm) 

class BaseRankRecipeFormSet(BaseFormSet):
	def clean(self):
		"""
		Adds validation 
		"""
		if any(self.errors):
			return None

		for form in self.forms:
			if form.cleaned_data:
				ranking = form.cleaned_data['ranking']

		# Check that all recipes have a ranking 
		if not ranking:
			raise forms.ValidationError(
				'All recipes must have a ranking.',
				code = 'missing_ranking')
	

foodapp/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from .models import Ingredient, Recipe, Relationship
from django.urls import reverse
from django.db import IntegrityError, transaction
from foodapp.forms import RankRecipeForm, BaseRankRecipeFormSet
from django.forms.formsets import BaseFormSet
from django.forms.formsets import formset_factory
from django.contrib import messages

import os
from mysite.settings import BASE_DIR
pulp_path = os.path.join(BASE_DIR, 'pulp/')


# Create your views here.

def index(request):
	#ingredient_list= Ingredient.objects.order_by('iid')[:20] # display on 10 first ingredients
	recipe_list= Recipe.objects.order_by('rid')[:20] # display on 10 first recipes
	#context = {'ingredient_list': ingredient_list}
	context = {'recipe_list': recipe_list}
	return render(request, 'foodapp/index.html', context)

def ingredient_detail(request, ingredient_id):
	ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
	return render(request, 'foodapp/ingredient-detail.html', {'ingredient': ingredient})

def preferences_ingredient(request, ingredient_id):
	ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
	return render(request, 'foodapp/preferences-ingredient.html', {'ingredient': ingredient})  

def recipe_detail(request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	return render(request, 'foodapp/recipe-detail.html', {'recipe': recipe})


def rank_ingredient(request, ingredient_id):
	#return HttpResponse("You're ranking ingredient %s." % ingredient_id)
	
	ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
	try:
		new_preference = request.POST['preference']
		ingredient.user_preference = new_preference


	    # TO BE CHANGED !
	except (KeyError, Ingredient.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'foodapp/ingredient.html', {
			'ingredient': ingredient,
			'error_message': "You didn't set up a value for your preferences.",
		})
	else:
		ingredient.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('foodapp:ingredient_detail', args=(ingredient.iid,)))

def run_model(request):
	return render(request, 'foodapp/run-model.html', {}) #POURQUOI CA MARCHE PAS ?
	#return HttpResponse("Give me a list of recommended recipes and a grocery list." )
	#return HttpResponseRedirect((reverse('foodapp:model_results'))


from .pulp.ilpmodel import foo, print_opt_recipes
def model_results(request):
	#return HttpResponse("Give me a list of recommended recipes and a grocery list." )
	list_selected_rid = print_opt_recipes()
	selected_recipes = Recipe.objects.filter(id__in=list_selected_rid).order_by('rid')
	context = {'selected_recipes' : selected_recipes}
	#return HttpResponse(output, content_type="text/plain")
	return render(request, 'foodapp/model-results.html', context)

def rank_output(request):
	# Create the formset, specifying the form and formset we want to use.
	#RankRecipeFormSet = formset_factory(RankRecipeForm, formset=BaseRankRecipeFormSet)
	RankRecipeFormSet = formset_factory(RankRecipeForm, formset=BaseFormSet)

	# Get our selected recipes from the ILP model for this user.  This is used as initial data.
	list_selected_rid = print_opt_recipes()
	selected_recipes = Recipe.objects.filter(id__in=list_selected_rid).order_by('rid')
	recipes_data = [{'rid': r.rid,'recipe_name': r.recipe_name, 'ranking': r.ranking} for r in selected_recipes]

	# if this is a POST request we need to process the form data
	if request.method == 'POST':
		#rankrecipe_formset = RankRecipeFormSet(request.POST, initial=recipes_data)

		rankrecipe_formset = RankRecipeFormSet(request.POST)

		if rankrecipe_formset.is_valid():
			# Save the data for each form in the formset
			new_rankings = []

			for rankrecipe_form in rankrecipe_formset:
				newranking = rankrecipe_form.cleaned_data.get('ranking')
				this_rid = rankrecipe_form.cleaned_data.get('rid')

				#if newranking:
					#new_rankings.append(UserLink(user=user, anchor=anchor, url=url))

				try:
					with transaction.atomic():
						#Replace the old ranking with the new ranking for this recipe
						this_recipe = Recipe.objects.filter(id=this_rid)
						this_recipe.ranking = newranking
						this_recipe.save(update_fields=['ranking'])

					# And notify our users that it worked
						messages.success(request, 'You have updated your ranking of this recipe.')

				except IntegrityError: #If the transaction failed
					messages.error(request, 'There was an error saving your ranking.')

	# if a GET (or any other method) we'll create a blank form
	else:
		rankrecipe_formset = RankRecipeFormSet(initial=recipes_data)

	context = {
		'rankrecipe_formset': rankrecipe_formset,
	}

	return render(request, 'foodapp/rank-output.html', context)
		

foodapp/templates/foodapp/index.html
{% load staticfiles %}

<html>
	<head>
		<title> Ingredients info </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<!-- <body>
		<h1> Home </h1>
			<h4> Rank some ingredients to begin : </h4>
		{% if ingredient_list %}
		    <ul>
		    {% for ing in ingredient_list %}
		        <li><a href="{% url 'foodapp:ingredient_detail' ing.iid %}">{{ ing.ingredient_name }}</a></li>
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No ingredients are available.</p>
		{% endif %}

			<h4> Or just get a recommendation <a href="{% url 'foodapp:run_model'%}"> right now </a> </h4>
	</body> -->

	<body>
		<h1> Home </h1>
			<h4> Rank some recipes to begin : </h4>
		{% if recipe_list %}
		    <ul>
		    {% for rec in recipe_list %}
		        <li><a href="{% url 'foodapp:recipe_detail' rec.rid %}">{{ rec.recipe_name }}</a></li>
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No recipes are available.</p>
		{% endif %}

			<h4> Or just get a recommendation <a href="{% url 'foodapp:run_model'%}"> right now </a> </h4>
	</body>

</html>		

foodapp/templates/foodapp/ingredient-detail.html
{% load staticfiles %}

<html>
	<head>
		<title> Ingredients info </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<body>

		<div>
			<h1>{{ ingredient.ingredient_name }}</h1>
			
			<h2> Preferences </h2>
				<p> Your preferences for this ingredient are : {{ingredient.user_preference}} </p>
				<p> Do you want to change them ? You can do it <a href="{% url 'foodapp:preferences_ingredient' 	ingredient.iid %}">here</a> </p>
			
			<h2> Nutrition </h2>
				<ul>
					<li> Calories per serving : {{ingredient.calories}} </li>
					<li> Fat per serving : {{ingredient.fat}}  </li>
					<li> Fiber per serving : {{ingredient.fiber}}  </li>
					<li> Sugar per serving : {{ingredient.sugar}}  </li>
					<li> Protein per serving : {{ingredient.protein}}  </li>
		</div>			
			
		
		<!-- <a href = {% url 'foodapp:index' %} > Back to homepage. </a> -->
		<div>
			<a href={% url 'foodapp:index' %} class="btn btn-default">Back to Homepage</a>
		</div>	
	</body>	
</html>	
		

foodapp/templates/foodapp/model-results.html
{% load staticfiles %}

<html>
	<head>
		<title> Fresh recommendendation </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<body>
		<h2> Fresh recommendations for you : </h2>
		{% if selected_recipes %}
		    <ul>
		    {% for recipe in selected_recipes %}
		        <li>
		        	<h4>{{ recipe.recipe_name }}</h4>
		        	<p> {{ recipe.instructions }} </p>
		        </li>
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No recipes are recommended.</p>
		{% endif %}

		<h3> Like it or not? Give us some <a href={% url 'foodapp:rank_output' %} >feedback</a> </h3>
		

		
		<a href = {% url 'foodapp:index' %} class="btn btn-default" > Back to homepage. </a>
	</body>
</html>				



 {% comment %}
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="{% url 'foodapp:rank_recipe' recipe.rid %}" method="post">
	{% csrf_token %}
	{% for recipe in selected_recipes %}
	    <input type="range" name="recipe-ranking" id="recipe{{ forloop.counter }}" value="{{ recipe.rid }}" min=0 		max=10 step=1 onchange="		updateTextInput(this.value);"/>
		<input type="text" id="textInput" value="">
			
		<script type="text/javascript">
			function updateTextInput(val) {
				document.getElementById('textInput').value=val; 
			}
		</script>
	{% endfor %}
	<input type="submit" value="Rank" />
	</form>
 {% endcomment %}

foodapp/templates/foodapp/preferences-ingredient.html
{% load staticfiles %}

<html>
	<head>
		<title> Ingredients info </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<body>

		<h1>Rank the ingredient {{ ingredient.ingredient_name }}</h1>
		
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		
		<form action="{% url 'foodapp:rank_ingredient' ingredient.iid %}" method="post">
		{% csrf_token %}
		<input type="range" name="preference" id="preference" value="value_preference" min=0 max=1 step=0.1 onchange="		updateTextInput(this.value);"/>
		<input type="text" id="textInput" value="">
		
		<script type="text/javascript">
			function updateTextInput(val) {
		          document.getElementById('textInput').value=val; 
		        }
		</script>
		
		
		<input type="submit" value="Submit my new taste!" />
		</form>
		
		<a href={% url 'foodapp:index' %} class="btn btn-default">Back to Homepage</a>
	</body>	
</html>	

foodapp/templates/foodapp/rank-output.html
{% load staticfiles %}

<html>
	<head>
		<title> Rank the recommendation we made for you : </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<body>

		<h2> Rank the recommendation we made for you : </h2>

		<div>
			{% comment %}
				{% if messages %}
			    	{% for message in messages %}
			        	<p>{{ message }}</p>
			    	{% endfor %}
				{% endif %}
			{% endcomment %}
			
			<form method="post">
			    {% csrf_token %}
			
				{{ rankrecipe_formset.management_form }}
			
			    {% for rankrecipe_form in rankrecipe_formset %}
			        <div class="rankrecipe_formset">
			            {{ rankrecipe_form.recipe_name }}  
			    
			            {{ rankrecipe_form.ranking }}
			            {% if rankrecipe_form.url.errors %}
			                {% for error in rankrecipe_form.url.errors %}
			                    {{ error|escape }}
			                {% endfor %}
			            {% endif %}
			        </div>
			    {% endfor %}
			
			    {% if rankrecipe_formset.non_form_errors %}
			        {% for error in rankrecipe_formset.non_form_errors %}
			            {{ error|escape }}
			        {% endfor %}
			    {% endif %}

		</div>

		    
		
		    <input type="submit" value="Update Rankings" class="button"/>
		</form>


		<!-- Include formset plugin - including jQuery dependency -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="{% static 'path_to/jquery.formset.js' %}"></script>
		<script>
		    $('.rankrecipe-formset').formset({
		        addRanking: 'add ranking',
		        deleteText: 'remove'
		    });
		</script>

		<a href={% url 'foodapp:index' %} class="btn btn-default">Back to Homepage</a>

	</body>
</html>		

  

foodapp/templates/foodapp/recipe-detail.html
{% load staticfiles %}

<html>
	<head>
		<title> Recipe info </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<body>

		<div>
			<h1>{{ recipe.recipe_name }}</h1>
			
			<h2> Preferences </h2>
				<p> Your preferences for this recipe are : {{recipe.ranking}} </p>
				<p> Do you want to change them ? You can do it <a href="{% url 'foodapp:preferences_ingredient' 	ingredient.iid %}">here</a> </p>
			
			<h2> Cooking information </h2>
				<ul>
					<li> Number of steps : {{recipe.number_steps}} </li>
					<li> Instructions: {{recipe.instructions}}  </li>

		</div>			
			
		
		<!-- <a href = {% url 'foodapp:index' %} > Back to homepage. </a> -->
		<div>
			<a href={% url 'foodapp:index' %} class="btn btn-default">Back to Homepage</a>
		</div>	
	</body>	
</html>	
		

foodapp/templates/foodapp/run-model.html
{% load staticfiles %}

<html>
	<head>
		<title> Ingredients info </title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/foodapp.css' %}">
	</head>	

	<body>

		<h1>Give me recipes ideas and a grocery list!</h1>
		<a href = {% url 'foodapp:model_results' %} > Go ! </a>

		<!--
		 <form action="{% url 'foodapp:model_results' %}" method="post">
		 {% csrf_token %}
		 <button type="button">Go!</button>
		 </form>
		--> 
	</body>
</html>		